/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : Help Menu
 #	author : miyako
 #	2015/11/16
 #
 # --------------------------------------------------------------------------------*/

// --- Help Menu
void HELP_SET_ENABLED(sLONG_PTR *pResult, PackagePtr pParams);
void HELP_Get_enabled(sLONG_PTR *pResult, PackagePtr pParams);
