/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-Help-Menu.h
 #	source generated by 4D Plugin Wizard
 #	Project : Help Menu
 #	author : miyako
 #	2022/10/11
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_HELP_MENU_H
#define PLUGIN_HELP_MENU_H

#include "4DPluginAPI.h"

#if VERSIONWIN
#include "shlwapi.h"
#else
#import <Cocoa/Cocoa.h>
#endif

#pragma mark -

void HELP_SET_ENABLED(PA_PluginParameters params);
void HELP_Get_enabled(PA_PluginParameters params);

#endif /* PLUGIN_HELP_MENU_H */
